version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  vib-backend:
    build:
      context: ./backend
    container_name: vib_backend_local
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env
    environment:
      # Override postgres host to use host machine's postgres
      - POSTGRES_HOST=host.docker.internal
    volumes:
      - ./backend:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  vib-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vib_frontend_local
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - NODE_PATH=./
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=http://vib-backend:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]