# Generated by Django 5.1 on 2025-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
