# Generated by Django 5.1 on 2025-02-07 15:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_youtubevideo_transcript'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='youtubevideo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript'], name='youtube_vid_transcr_5369cd_gin'),
        ),
    ]
