# Generated by Django 5.1 on 2025-02-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_youtubevideo_youtube_vid_transcr_5369cd_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
